name: CI - Backend + Frontend + Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_BASE: http://localhost:6007/api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Start backend
        run: |
          cd backend
          npm run dev &
        env:
          MONGO_URI: ${{ env.MONGO_URI }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          PORT: ${{ env.PORT }}

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:${{ env.PORT }}/api/auth/login

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start frontend
        run: |
          cd frontend
          npm run dev &
        env:
          VITE_API_BASE: ${{ env.VITE_API_BASE }}

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000

      - name: Install and run Playwright tests
        run: |
          cd tests
          npm install
          npx playwright install
          npx playwright test
