name: CI - Clonando App y Ejecutando Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_BASE: http://localhost:6007/api

    steps:
      - name: Checkout repo actual (con el workflow)
        uses: actions/checkout@v3

      - name: Clonar repo Athena Redux Bank
        run: |
          git clone https://github.com/Atenea-Conocimientos/redux-athena-bank.git app
      - name: Crear archivo .env para backend
        run: |
          echo "MONGO_URI=${{ env.MONGO_URI }}" >> app/backend/.env
          echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> app/backend/.env
          echo "PORT=${{ env.PORT }}" >> app/backend/.env
      - name: Instalar dependencias backend
        run: |
          cd app/backend
          npm install
      - name: Levantar backend
        run: |
          cd app/backend
          npm run dev > backend.log 2>&1 &
        env:
          MONGO_URI: ${{ env.MONGO_URI }}
          JWT_SECRET: ${{ env.JWT_SECRET }}
          PORT: ${{ env.PORT }}

      - name: Instalar wait-on
        run: npm install -g wait-on

      - name: Esperar backend
        run: wait-on tcp:6007

      - name: Instalar dependencias frontend
        run: |
          cd app/frontend
          npm install
      - name: Levantar frontend
        run: |
          cd app/frontend
          npm run dev > frontend.log 2>&1 &
        env:
          VITE_API_BASE: ${{ env.VITE_API_BASE }}

      - name: Esperar frontend
        run: wait-on http://localhost:3000

      - name: Instalar dependencias de Playwright
        run: |
          sudo apt-get update
          # Instalar dependencias para navegadores de Playwright
          sudo apt-get install -y libgtk-3-0 libgbm1 libnotify-dev libgconf-2-4 libnss3 libxss1 xvfb
          # Dependencias adicionales que podrían ser necesarias
          sudo apt-get install -y libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0

      - name: Instalar y correr tests (proyectos setup + chromium)
        run: |
          npm install
          npx playwright install --with-deps
          npx playwright test --reporter=html
      - name: Guardar reportes como artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
