name: CI - clonando App y ejecutando tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        
        services:
            mongo:
                image: mongo:6.0
                ports:
                    - 27017:27017

        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            PORT: 6007
            VITE_API_URL: http://localhost:6007/api

        steps:
            - name: Checkout repo actual (con el workflow)
              uses: actions/checkout@v3

            - name: Clonar repo Athena Redux Bank
              run: |
                git clone https://github.com/Atenea-Conocimientos/redux-athena-bank.git app
        
            - name: Crear archivo .env para backend
              run: |
                echo "MONGO_URI=${{ env.MONGO_URI }}" > app/backend/.env
                echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> app/backend/.env
                echo "PORT=${{ env.PORT }}" >> app/backend/.env
                echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> app/backend/.env

            - name: Instalar dependencias de backend
              run: |
                cd app/backend
                npm install
        
            - name: Construir backend
              run: |
                cd app/backend
                npm run dev > backend.log 2>&1 &
        
            # se instala la herramienta wait-on  globalmente
            - name: Instalar wait-on
              run: npm install -g wait-on

            # esperar que el backend se levante en el puerto 6007
            - name: Esperar backend
              run: wait-on tcp:6007

            # Instalar dependencias del frontend
            - name: Instalar dependencias frontend
              run: |
                cd app/frontend
                npm install
              env:
                VITE_API_URL: ${{ env.VITE_API_URL }}

            #esperar que se levante el front
            - name: Esperar frontend
              run: wait-on http://localhost:3000
          

        

    